travis:
  secure:
    BINSTAR_TOKEN: lUYx40cl8qbvXfcYKWMBjaU60zZx30zg5CB/u3FlRyTcggsRjcnvNI5ifp7pO5s4UNEr1Z3S/8hiuEHjvXvCrX3VA9rroo9kDrq+gpfrBDphe4jJfV/SUTVPXb5l8DkCwUlEgQlX3i5H2GCw5YLBXR4kEOlT+Dt+89GLqguLv59fuhU1kklSF/Y7gq2XAfeAoTmG/22LnQdBxmFBTP4bVsXRl/itcUcmfql8m/4Qe5jiN4xgh03C61j+VSCoDyuEJYgNacyk3znSgo9U3lPxTnocXsz+27pRWtYsFFDckgF2tUnIAlIexyz4sj/OQOfTohTnu8SbQiavTHpagUCubiL3OAyZVXiULilpUzfFTVLfUfTJh8XfkqlhLMZrle53A9AniyKoHKNoV0Joz0AiFNDAYjUhrJs3/NlO4CBBJajMXSFGt+MQHFhCoUpKLCXZwsFJzztIDYB/BbxrfSRYvzacn0j818yD1TexSVe+3CUDT4zIE2ud3b5ZASG7JbYY4UR25Xw7YEpFdC5n4xRA5YjRGxkuTJW34PZ1dw0M4xx7uT2O6NZN9C64c9pWn62UyVp3BnjubjQMd9oH7HcfyjWs4s9ghaJF9JNjZXNOsX2/R+KBRXyNOiWTXZUn974M8tc15emxfcoUlp53VptofGWt+q8SURnD7QBfbha8kXE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
