travis:
  secure:
    BINSTAR_TOKEN: AdU6TUVUO9I5eDLgA26L/dzPQZYLThTCw1fp2nl0MtRAzYhsBuA0MWUkXU7on+8kH858GqfgmyU2VZwiji9tat018Oi+gNfAF0cppexXfhmVDx10IyspD/54Fnvh2CUtFjQ4odg0f4o7tlPf9y/rm43OUtN+iuXHw40OZACW0AgvuBvgouAl+CgBKWrfupp26dh9axoiwuLRJRVOfvx2JFCcgd5VWet8XNz58vvuvjLQavpTcPG8cfsgPAsXDIN/BWtIfS+LBY+asY/3MhmybptqHLnqR+hsQqd8YB9LuvQtC2y1m/GkhAN37K/AV4Lr3tjIWx8X0sYh2047IQUjjU82wS19+i2zDgZgRmyLYjiTv1oft7oiBlUjTSYCePu8KWWenSfN5ikMbev1FTX6EM1pOG2IKgBptjGs0zGPLxA8bMJ9Xvx76POixfVnRd+sM0Std+EZKefPBZUAiebQ+g+fQKOATN08bBKoebSjtxfH/pKokgp4xlmaholrQNCMdSf/hFlgs98jIwponqBs55JDLJRiNHv87mQrRuPOU+/Y3ZmLZGLIzEGPAiars9ICVmbM3C6gUGb+150jqVkA9fOE3zznS3k+h4NopQUYyOcTFMdMdRDrOqhv0kNEu+JAnStn54ydVk2ZDuGwjoXWvkWbuqb/YKVT8gdWFM8J96k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
